- alias: 'Set theme at startup'
  initial_state: 'on'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: oxfordblue 

- alias: 'Nest Home at 3pm'
  initial_state: 'on'
  trigger:
      platform: time
      at: '15:00:00'
  action:
    - service: script.turn_on
      entity_id: script.nest_home
    - service: notify.pushover
      data_template:
        title: "Nest Home"
        message: >
          "Nest Home {{ states.input_text.nest_mode.state }}"
        data:
          sound: pianobar
          priority: 0
      
- alias: 'Turn On Outside Lights at Sunset'
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:15:00"
  action:
    - service: homeassistant.turn_on
      entity_id: group.outside_back_lights, group.outside_front_lights, switch.living_room_lamp,switch.study_light
    - service: notify.pushover
      data:
        title: "Outside Lights On"
        message: "Outside Lights On - Sunset"
        data:
          sound: pianobar
          priority: 0
          
- alias: 'Turn Off Back Lights 945p'
  initial_state: 'on'
  trigger:
    platform: time
    at: '21:45:00'
  action:
    service: homeassistant.turn_off
    entity_id: group.Outside_Back_Lights

- alias: 'Garage Open Lights On'
  initial_state: 'on'
  trigger:
  -  platform: state
     entity_id: cover.garage_door
     to: 'open'
     #  -  platform: state
     #entity_id: lock.front_door_lock
     #to: 'unlocked'
  condition: 
    condition: or
    conditions:
      - condition: time
        after: '17:30:00'
      - condition: time
        before: '02:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: group.Inside_Lights

- alias: 'Front Door Unlocked Lights On'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.kwikset_touchpad_electronic_deadbolt_alarm_type_10
    to: "19"
  condition:  
    condition: or
    conditions:
      - condition: time
        after: '17:30:00'
      - condition: time
        before: '02:00:00'
  action:
    service: homeassistant.turn_on 
    entity_id: group.inside_lights

- alias: 'Front Door Unlocked Code'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.kwikset_touchpad_electronic_deadbolt_alarm_type_10
    to: "19" 
  action:
    - service: script.turn_on
      entity_id: script.nest_home
    - service: shell_command.bi_home 
    - service: alarm_control_panel.alarm_disarm
      data: 
        entity_id: alarm_control_panel.buck_creek
        code: !secret envisalinkcode
    - service: notify.pushover
      data:
        title: "Front Door"
        message: "Keypad Unlock"
        data:
          sound: cosmic
          priority: 0
      
#- alias: 'Turn Off Holiday Lights'
#  initial_state: 'off'
#  trigger:
#    platform: time
#    at: '00:00:00'
#  action:
#    - service: homeassistant.turn_off
#      entity_id: group.Holiday_Lights
#    - service: homeassistant.turn_on
#      entity_id: group.Outside_Front_Lights
    
- alias: 'Turn Off Outside Lights at Sunrise'
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunrise
  action:
    service: homeassistant.turn_off
    entity_id: group.Outside_Back_Lights, group.Outside_Front_Lights
    
- alias: 'Garage Door Open'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: cover.garage_door
    to: 'open'
  action:
    - service: script.turn_on
      entity_id: script.nest_home
    - service: shell_command.bi_home
    - service: notify.pushover
      data:
        title: "Garage Open"
        message: "Garage Door Open"
        data:
          sound: magic
          priority: 0
    - service: alarm_control_panel.alarm_disarm
      data: 
        entity_id: alarm_control_panel.buck_creek
        code: !secret envisalinkcode
        
- alias: 'Garage Door Closed'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: cover.garage_door
    to: 'closed'
  action:
    service: notify.pushover
    data:
      title: "Garage Closed"
      message: "Garage Door Closed"
      data:
        sound: magic
        priority: 0
  

        #- alias: 'Front Door Unlocked with Code'
        #  initial_state: 'on'
        #  trigger:
        #    platform: state
        #    entity_id: sensor.kwikset_touchpad_electronic_deadbolt_alarm_type_10
        #  action:
        #  - service: script.turn_on
        #    entity_id: script.nest_home
        #  - service: shell_command.bi_home
        #  - service_template: >
        #      {% if ( (trigger.to_state.state == "19") ) %}
        #        notify.pushover
        #      {% else %}
        #        script.dummy_script
        #      {% endif %}
        #    data:
        #      title: "Front Door"
        #      message: "Keypad Unlock"
        #      data:
        #        sound: cosmic
        #        priority: 0
      

#- alias: 'Front Door Unlocked Code'
  #  initial_state: 'on'
  #  trigger:
  #    platform: state
  #    entity_id: sensor.kwikset_touchpad_electronic_deadbolt_alarm_type_10
  #  action:
  #  - service: script.turn_on
  #    entity_id: script.nest_home
  #  - service_template: >
  #      {% if ( (trigger.to_state.state == "19") ) %}
  #        shell_command.bi_home 
  #      {% else %}
  #        script.dummy_script
  #      {% endif %}
  #  - service_template: >
  #      {% if ( (trigger.to_state.state == "19") ) %}
  #        alarm_control_panel.alarm_disarm
  #      {% else %}
  #        script.dummy_script
  #      {% endif %}
  #    data: 
  #      entity_id: alarm_control_panel.buck_creek
  #      code: !secret envisalinkcode
  #  - service_template: >
  #      {% if ( (trigger.to_state.state == "19") ) %}
  #        notify.pushover
  #      {% else %}
  #        script.dummy_script
  #      {% endif %}
  #    data:
  #      title: "Front Door"
  #      message: "Keypad Unlock"
  #      data:
  #        sound: cosmic
  #        priority: 0


- alias: "ALARM TRIGGERED"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: alarm_control_panel.buck_creek
    to: triggered
  action:
  - service: notify.pushover
    data:
      title: "ALARM TRIGGERED"
      message: "Buck Creek Alarm Triggered"
      data:
        sound: updown
        priority: 1
  - service: homeassistant.turn_on
    entity_id: group.inside_lights, group.outside_front_lights, group.outside_back_lights

- alias: "Alarm Armed Away"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: alarm_control_panel.buck_creek
    to: armed_away 
  action:
          #- service: script.turn_on
          #entity_id: script.nest_eco
    - service: notify.pushover
      data:
        title: "ALARM ARMED"
        message: "Armed Away"
        data:
          sound: bike 
          priority: 0

- alias: "Alarm Armed Stay"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: alarm_control_panel.buck_creek
    to: armed_home
  action:
          #- service: script.turn_on
          #entity_id: script.nest_eco
    - service: notify.pushover
      data:
        title: "ALARM ARMED"
        message: "Armed Stay"
        data:
          sound: bike 
          priority: 0

        #- alias: "Alarm Armed Night"
        #  initial_state: 'on'
        #  trigger:
        #    platform: state
        #    entity_id: alarm_control_panel.buck_creek
        #    to: armed_night
        #  action:
        #    service: notify.pushover
        #    data:
        #      title: "ALARM ARMED"
        #      message: "Armed Stay"
        #      data:
        #        sound: bike 
        #        priority: 1

- alias: 'Disable Alarm at 5:30'
  initial_state: 'on'
  trigger:
    platform: time 
    at: '05:30:00'
  action:
    - service: alarm_control_panel.alarm_disarm
      data: 
        entity_id: alarm_control_panel.buck_creek
        code: !secret envisalinkcode

- alias: 'Fridge Door Left Open'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.ingersoll_rand_dwzwave1_sensor
      to: 'on'
      for:
        minutes: 2
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.fridge_door_open
  condition:
    condition: state
    entity_id: binary_sensor.ingersoll_rand_dwzwave1_sensor
    state: 'on'
  action:
    - service: notify.pushover
      data:
        title: "Fridge Open"
        message: "Fridge Open"
        data:
          sound: gamelan
          priority: 0
    - service: timer.start
      entity_id: timer.fridge_door_open

- alias: 'Someone Home'
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: group.family_presence
      to: 'home'
  action:
    - service: notify.pushover
      data:
        title: "Someone Home"
        message: "Someone is Home"
        data:
          sound: pianobar
          priority: 0

- alias: 'Everyone Away'
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: group.family_presence
      to: 'not_home'
  action:
    - service: notify.pushover
      data:
        title: "All Devices Away"
        message: "All Devices Away"
        data:
          sound: pianobar
          priority: 0

- alias: 'Notify Cert Expire'
  initial_state: 'on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.ssl_certificate_expiry
      below: 10
  action:
    service: notify.pushover
    data:
      title: "Cert Expire"
      message: "Cert Expire 10 days"
      data:
        sound: pianobar
        priority: 0

- alias: 'Front Door Battery Update'
  initial_state: 'on'
  trigger:
    - platform: time
      minutes: '/30'
      seconds: 0
  action:
    - service: input_boolean.toggle 
      entity_id: input_boolean.update_battery_level
      
- alias: 'Restart HA'
  initial_state: 'off'
  trigger:
    platform: time
    at: '18:05:00'
  action:
    service: homeassistant.restart
