- platform: mjpeg
  mjpeg_url: http://172.16.1.25:81/mjpg/Drvwy
  name: Driveway

- platform: mjpeg
  mjpeg_url: http://172.16.1.25:81/mjpg/FrntPorch
  name: FrontPrch

- platform: mjpeg
  mjpeg_url: http://172.16.1.25:81/mjpg/BackYrd2
  name: BackYrd2

- platform: mjpeg
  mjpeg_url: http://172.16.1.25:81/mjpg/BackPrch
  name: BackPrch

- platform: mjpeg
  mjpeg_url: http://172.16.1.25:81/mjpg/Garage
  name: Garage

- platform: ring
  
- platform: generic
  still_image_url: http://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=EWX&brand=wui&num=1&delay=15&type=N0R&frame=0&scale=1.000&noclutter=0&lat=0&lon=0&label=you&showstorms=1&map.x=400&map.y=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=1&rainsnow=0&lightning=0&smooth=0%22%20alt=%22Austin-San%20Antonio%20radar%20map%22%3E
  #still_image_url: https://radar.weather.gov/radar.php?rid=ewx&product=N0R&overlay=11101111&loop=no