homeassistant:
  name: Home
  latitude: !secret latitude 
  longitude: !secret longitude
  elevation: 365
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

frontend:
  themes: !include themes.yaml

camera: !include cameras.yaml

shell_command: !include shell_commands.yaml

logger:
  default: warning 

config:

http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

updater:
discovery:
conversation:
history:
logbook:
sun:
sensor: !include sensors.yaml

weather:
  - platform: darksky
    api_key: !secret darkskyapi
    mode: daily

tts:
  - platform: google

cloud:
  alexa:
   filter:
     include_entities:
       - switch.kitchen_counter
       - switch.kitchen_island
       - switch.front_hall_lights
       - switch.play_room_light
       - switch.study_light
       - switch.back_porch_lights
       - switch.deck_lights
       - switch.living_room_lamp
       - lock.front_door_lock
       - lock.back_door_lock
       - switch.bedroom_lampk

notify:
  - name: pushover
    platform: pushover
    api_key: !secret pushoverapi
    user_key: !secret pushoveruser

  # - platform: command_line
  #   name: "notify_kitchen_echo"
  #   command: 'python /config/alexa/alexa_wrapper.py -d {{ "-lastalexa" }}'
          
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: https://172.16.1.180:3218
  ide:
    title: IDE
    icon: mdi:atom
    url: https://ha.mostlychris.com:8321/ide.html
  grafana:
    title: Grafana
    icon: mdi:finance
    url: https://ha.mostlychris.com:3000/ 
  portainer:
    title: Portainer
    icon: mdi:harddisk
    url: https://ha.mostlychris.com:9000/ 

nest:
  client_id: !secret nestclientid
  client_secret: !secret nestclientsecret
    

envisalink:
  host: 172.16.1.144
  panel_type: DSC
  user_name: user
  password: user
  code: !secret envisalinkcode
  port: 4025
  evl_version: 4
  keepalive_interval: 60
  zonedump_interval: 30
  zones:
    1:
     name: 'Front_Garage Door Entry'
     type: 'opening'
    2:
     name: 'Back Doore Entry'
     type: 'opening'
    3:
     name: 'Upstairs Windows'
     type: 'opening'
    4:
     name: 'Kitchen Dining Windows'
     type: 'opening'
    5:
     name: 'Living Room Windows'
     type: 'opening'
    6:
     name: 'Kitchen_Living Motion'
     type: 'motion'
    7:
     name: 'Master Windows'
     type: 'opening'
    8:
     name: 'Study Windows'
     type: 'opening'
    9:
     name: 'Upstairs Motion'
     type: 'motion'
    10:
     name: 'Front Hall Motion'
     type: 'motion'
  partitions:
    1:
      name: 'Buck Creek'


zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwavenetworkkey

input_text:
  nest_mode:
    name: Heating/Cooling Mode

input_boolean:
  update_battery_level:
    name: Update Battery Level

lovelace:
  mode: yaml

device_tracker:
  - platform: unifi
    host: 172.16.1.117
    verify_ssl: false
    username: !secret unify_user
    password: !secret unify_pass
    consider_home: 180 
    detection_time: 60
    new_device_defaults:
      track_new_devices: false
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: true
    mqtt_topic: "owntracks/#"
    events_only: true

zone: !include zones.yaml
  

timer:
  fridge_door_open:
    duration: '00:03:00'

neato:
  username: !secret neatouser
  password: !secret neatopass

ring:
  username: !secret ringuser
  password: !secret ringpass
  
influxdb:
  host: ha.mostlychris.com 
  port: 8086
  database: homeassistant
  max_retries: 9 
  default_measurement: state
  
rachio:
  api_key: !secret rachio_api
  manual_run_mins: 30
  
recorder:
  purge_keep_days: 2

utility_meter:
  energy:
    source: sensor.aeotec_dsb28_home_energy_meter_2nd_edition_energy
    cycle: monthly

system_health:

media_player:
  - platform: alexa
    email: !secret alexa_email
    password: !secret alexa_password
    url: "amazon.com"

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload
    
custom_updater:
