resources:
  - url: /local/mini-graph-card-bundle.js?v=0.2.2
    type: module

title: Home 
views:
  - !include home.yaml
  - !include weather.yaml
  - !include camerapage.yaml
  - !include sensorpage.yaml
  - !include presencepage.yaml
  - !include sysinfopage.yaml
  - !include miscpage.yaml






