#resources:
#  - url: /local/custom-lovelace/thermostat-card/thermostat-card.js?v=1
#    type: module
#- url: /local/simple-thermostat/simple-thermostat.js?v=1.01
#  type: module


###############
## HOME PAGE ##
###############

title: Home
views:
  - title: Home 
    icon: mdi:castle
    cards:
      - type: entity-filter
        entities:
          - entity: switch.kitchen_counter
            icon: mdi:lightbulb
            name: Ktch Cntr
            tap_action:
              action: toggle
          - entity: switch.kitchen_island
            icon: mdi:lightbulb
            name: Ktch Isld
            tap_action:
              action: toggle
          - entity: switch.play_room_light
            icon: mdi:lightbulb
            name: Play Rm
            tap_action:
              action: toggle
          - entity: switch.deck_lights
            icon: mdi:lightbulb
            name: Deck
            tap_action:
              action: toggle
          - entity: switch.front_porch_lights
            icon: mdi:lightbulb
            name: F Prch
            tap_action:
              action: toggle
          - entity: switch.driveway_lights
            icon: mdi:lightbulb
            name: Drvwy
            tap_action:
              action: toggle
          - entity: switch.front_hall_lights
            icon: mdi:lightbulb
            name: F Hall
            tap_action:
              action: toggle
          - entity: switch.back_porch_lights
            icon: mdi:lightbulb
            name: B Prch
            tap_action:
              action: toggle
          - entity: switch.study_light
            icon: mdi:lightbulb
            name: Study
            tap_action:
              action: toggle
          - entity: switch.living_room_lamp
            icon: mdi:lightbulb
            name: Lv Rm Lmp
            tap_action:
              action: toggle
        state_filter:
          - "on"
        card: 
          type: glance
          show_state: false
          columns: 3
      - type: glance
        state_filter:
          - "detected"
          - "on"
        entities:
          - entity: binary_sensor.front_hall_motion
            name: "Front Hall" 
          - entity: binary_sensor.kitchen_living_motion
            name: "Kitchen"
          - entity: binary_sensor.upstairs_motion
            name: "Upstairs"
          - entity: binary_sensor.buck_creek_away
            name: "Nest Away"
            #      - type: entities
            #        entities:
            #          - entity: group.door_status
            #            icon: mdi:door
            #          - entity: alarm_control_panel.buck_creek
            #          - entity: group.motion_sensors
      - type: glance
        show_state: false
        entities:
          - entity: script.alarm_arm_night
            name: Arm Night
            tap_action:
              action: toggle
            icon: mdi:weather-night
          - entity: script.alarm_arm_stay
            name: Arm Stay
            tap_action:
              action: toggle
            icon: mdi:home-account
          - entity: script.alarm_arm_away
            name: Arm Away
            tap_action:
              action: toggle
            icon: mdi:home-lock
          - entity: alarm_control_panel.buck_creek
            Name: Alarm
#      - type: alarm-panel
#        name: Alarm
#        entity: alarm_control_panel.buck_creek
      - type: glance
        show_state: false
        entities:
        - entity: lock.front_door_lock
          name: Front
          tap_action:
            action: toggle
        - entity: sensor.batt_frontdoor
          name: Batt 
        - entity: lock.back_door_lock
          name: Back
          #icon: mdi:lock
          tap_action:
            action: toggle
        - entity: sensor.batt_backdoor
          name: Batt
        - entity: cover.garage_door
          name: Garage
      - type: vertical-stack
        cards:
        - type: glance
          entities:
            - entity: sensor.downstairs_thermostat_downstairs_hvac_state
              name: Downstairs
              icon: mdi:air-conditioner
            - entity: binary_sensor.downstairs_thermostat_downstairs_fan
              name: DN Fan
              icon: mdi:fan
            - entity: sensor.upstairs_thermostat_upstairs_hvac_state
              name: Upstairs
              icon: mdi:air-conditioner
            - entity: binary_sensor.upstairs_thermostat_upstairs_fan
              name: UP Fan
              icon: mdi:fan
            - entity: script.nest_eco
      - type: vertical-stack
        cards:
          - type: thermostat
            entity: climate.downstairs_downstairs
            name: Downstairs
          - type: thermostat
            entity: climate.upstairs_upstairs
            name: Upstairs
      - type: glance
        columns: 3
        show_state: false
        entities:
        - entity: switch.kitchen_island
          name: Island
          icon: mdi:lightbulb
          tap_action:
            action: toggle
        - entity: switch.kitchen_counter
          name: Counter
          icon: mdi:lightbulb
          tap_action:
            action: toggle
        - entity: switch.front_hall_lights
          name: Front Hall
          icon: mdi:lightbulb
          tap_action:
            action: toggle
        - entity: switch.study_light
          name: Study
          icon: mdi:lightbulb
          tap_action:
            action: toggle
        - entity: switch.play_room_light
          name: Play Rm
          icon: mdi:lightbulb
          tap_action:
            action: toggle
        - entity: switch.living_room_lamp
          name: Lvng Rm Lmp
          icon: mdi:lamp
          tap_action:
            action: toggle
      - type: glance
        columns: 4
        show_state: false
        entities:
        - entity: switch.deck_lights
          name: Deck
          icon: mdi:lightbulb
          tap_action:
            action: toggle
        - entity: switch.back_porch_lights
          name: Back Porch
          icon: mdi:lightbulb
          tap_action:
            action: toggle
        - entity: switch.front_porch_lights
          name: Front Porch
          icon: mdi:lightbulb
          tap_action:
            action: toggle
        - entity: switch.driveway_lights
          name: Driveway
          icon: mdi:lightbulb
          tap_action:
            action: toggle
      - type: glance
        show_state: false
        entities:
          - entity: switch.adsb
            name: ADSB
          - entity: switch.attic_switch
            name: Attic Switch
            
            
##############
#Weather Page#
##############

  - title: Weather
    icon: mdi:weather-partlycloudy
    cards:
      - type: vertical-stack
        cards:
          - type: weather-forecast
            entity: weather.dark_sky
          - type: glance 
            entities:
              - entity: sensor.pws_alerts
                name: Alerts
              - entity: sensor.pws_temp_f
                name: Temp
              - entity: sensor.pws_feelslike_f
                name: Feel
              - entity: sensor.pws_precip_today_in
                name: Rain
      - type: entities
        entities:
          - sensor.pws_precip_1d
          - sensor.pws_weather_1d
          - sensor.pws_weather_1n
          - sensor.pws_weather_2d
          - sensor.pws_weather_2n
          - sensor.pws_weather_3d
          - sensor.pws_weather_3n
          - sensor.pws_weather_4d
          - sensor.pws_weather_4n
      - type: vertical-stack
        cards:
          - type: history-graph
            entities:
              - entity: sensor.pws_temp_f
                name: Outside
              - entity: sensor.downstairs_thermostat_downstairs_temperature
                name: Downstairs
              - entity: sensor.upstairs_thermostat_upstairs_temperature
                name: Upstairs
            hours_to_show: 36
          - type: history-graph
            entities:
              - entity: sensor.pws_precip_today_in
                name: Rain
            hours_to_show: 24
      - type: picture-entity
        entity: camera.generic_camera

#################
## CAMERA PAGE ##
#################

  - title: Cameras 
    icon: mdi:cctv
    cards:
      - type: picture-entity
        entity: camera.driveway
      - type: picture-entity
        entity: camera.frontprch
      - type: picture-entity
        entity: camera.front_door
      - type: picture-entity
        entity: camera.backprch
      - type: picture-entity
        entity: camera.backyrd2
      - type: picture-entity
        entity: camera.garage

#################
## SENSOR PAGE ##
#################

  - title: Sensors 
    icon: mdi:smoke-detector
    cards:
      - type: entities
        entities:
          - entity: sensor.kitch_last_tripped
            name: Kitch Last Tripped
      - type: history-graph
        entities:
                #- entity: binary_sensor.kitchen_living_motion
                #  name: "Kitch/Dine"
          - entity: cover.garage_door
            name: "Garage"
          - entity: binary_sensor.back_doore_entry
            name: "Bk Door"
          - entity: binary_sensor.front_garage_door_entry
            name: "Frnt/Grge"
          - entity: binary_sensor.ingersoll_rand_dwzwave1_sensor
            name: "Frdg Door"
        hours_to_show: 4 
      - type: history-graph
        entities:
          - entity: sensor.downstairs_thermostat_downstairs_hvac_state
            name: DN
          - entity: sensor.upstairs_thermostat_upstairs_hvac_state
            name: UP 
        hours_to_show: 12
      - type: glance 
        entities:
          - entity: binary_sensor.front_hall_motion
            name: "Front Hall" 
          - entity: binary_sensor.kitchen_living_motion
            name: "Kitchen"
          - entity: binary_sensor.upstairs_motion
            name: "Upstairs"
          - entity: binary_sensor.buck_creek_away
            name: "Nest Away"
      - type: glance 
        entities:
          - entity: binary_sensor.kitchen_dining_windows
            name: "Kch/Dine" 
          - entity: binary_sensor.living_room_windows
            name: "Living"
          - entity: binary_sensor.master_windows
            name: "Master"
          - entity: binary_sensor.study_windows
            name: "Study"
      - type: glance 
        entities:
          - entity: binary_sensor.back_doore_entry
            name: "Back" 
          - entity: binary_sensor.front_garage_door_entry
            name: "Frnt/Grge" 
          - entity: cover.garage_door
            name: "Garage"
          - entity: binary_sensor.ingersoll_rand_dwzwave1_sensor
            name: "Fridge"
      - type: glance
        entities:
          - entity: sensor.connor_room_nest_protect_color_status
            name: "Connor"
            icon: mdi:smoke-detector
          - entity: sensor.living_room_nest_protect_color_status
            name: "Living Rm"
            icon: mdi:smoke-detector
          - entity: sensor.upstairs_nest_protect_color_status
            name: "Up Hall"
            icon: mdi:smoke-detector
      - type: vertical-stack
        cards:
        - type: entities 
          entities:
            - entity: sensor.plex
        - type: entities
          entities: 
            - entity: vacuum.clarence
        - type: picture-entity
          entity: camera.clarence_cleaning_map

###############################
## PRESENCE and MAPPING PAGE ##
###############################

  - title: Presence 
    icon: mdi:map-marker
    cards:
      - type: history-graph
        entities:
          - entity: group.chris_presence
            name: "Chris"
          - entity: device_tracker.449160b9e8ef
            name: "Allyson"
          - entity: device_tracker.adsb
            name: ADSB
          - entity: group.family_presence
            name: "All Devices"
        hours_to_show: 8
      - type: entity-filter
        show_state: true
        entities:
          - entity: device_tracker.adsb
            icon: mdi:laptop
          - entity: device_tracker.attic_pc
            icon: mdi:laptop
            #- entity: device_tracker.449160859d18
            #  name: Chris
            #  icon: mdi:cellphone-android
          - entity: device_tracker.449160b9e8ef
            name: Allyson
            icon: mdi:cellphone-android
            #- entity: device_tracker.chriss9_phone
            #  name: Chris OT
            #  icon: mdi:cellphone-android
          - entity: group.chris_presence
            name: Chris
            icon: mdi:cellphone-android
          - entity: device_tracker.ooma
            name: OOMA
            icon: mdi:phone
        state_filter:
          - "home"
          - "work"
        card:
          type: glance
          show_state: true
      - type: glance
        entities:
          - entity: sensor.downstairs_away_mode
            name: "Downstairs"
          - entity: sensor.upstairs_away_mode
            name: "Upstairs"
          - entity: sensor.to_home
            name: "Home"
            icon: mdi:car
          - entity: sensor.to_work
            name: "Work"
            icon: mdi:car
      - type: vertical-stack
        cards:
        - type: history-graph
          entities:
            - entity: sensor.to_home
              name: "To Home"
          hours_to_show: 48
        - type: history-graph
          entities:
            - entity: sensor.to_work
              name: "To Work"
          hours_to_show: 48
      - type: map
        aspect_ratio: 4:3
        default_zoom: 16
        entities:
          - device_tracker.chriss9_phone
          - zone.home
          - zone.work

######################
## SYSTEM INFO PAGE ##
######################

  - title: System
    icon: mdi:desktop-classic
    cards:
      - type: entities 
        entities:
          - entity: sensor.ssl_certificate_expiry
            name: Let's Encrypt Cert  
          - entity: sensor.disk_use_percent
            name: Disk Use
          - entity: sensor.load_5m
            name: Load 5m
          - entity: sensor.memory_use
            name: Mem Used
          - entity: sensor.processor_use
            name: Proc Use
      - type: entities 
        entities:
          - entity: sensor.pi_hole_dns_unique_clients
          - entity: sensor.pi_hole_dns_unique_domains
          - entity: sensor.pi_hole_ads_percentage_blocked_today
          - entity: sensor.pi_hole_ads_blocked_today
          - entity: sensor.pi_hole_dns_queries_today

###############
## MISC PAGE ##
###############

  - title: Other
    icon: mdi:space-invaders
    cards:
      - type: entities
        entities:
          - entity: sensor.avian_flu_symptoms
          - entity: sensor.next_launch
