resources:
  - url: /local/mini-graph-card-bundle.js?v=0.2.2
    type: module
    
  - url: /local/custom-lovelace/card-tools.js?v=0.4
    type: js

  - url: /local/custom-lovelace/fold-entity-row.js?v=0.86
    type: js
    
title: Home 
views:
  - !include home.yaml
  - !include weather.yaml
  - !include camerapage.yaml
  - !include sensorpage.yaml
  - !include presencepage.yaml
  - !include sysinfopage.yaml
  - !include miscpage.yaml






